name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時に実行
  push:
    branches: [main]     # main ブランチに push されたときにも実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate github profile summary cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Makoto041
