name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  issues: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate github profile summary cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Makoto041
          TOKEN: ${{ secrets.TOKEN }}  
